### ISSUE TITLE
`id 相邻的 page 在物理存储上同样相邻`感觉这句话不对

### ISSUE THREAD

**Issue by fananchong** [ZhengHe-MD/learn-bolt#3]
好像操作系统有页表，来关联虚拟内存地址与磁盘块
因此连续的虚拟内存地址，或者说 bolt 相邻的 logic page ，不一定在物理存储上也是相邻的
只能保证同个 logic page 内的修改，大概率在物理存储上是连续的修改

**Comment by ZhengHe-MD** [comment]
@fananchong 不好意思才看到，我认为你说的是对的。

https://github.com/ZhengHe-MD/learn-bolt/pull/4

如果你有看到的话辛苦 review 一下，谢谢！
